### PR TITLE
Bump event API compatibility and prepare for v4.0.0 release

### LINKED ISSUE #11: The plugin does not install for logstash 5.0.2
I've been trying to install logstash-input-websocket using the command 
`bin/logstash-plugin install logstash-input-websocket` 

Every time I try to do that, I get an error. PFB the image. 

image

- Version: Logstash 5.0.2
- Operating System: OpenSUSE 13.2
- Steps to Reproduce: Try and install the plugin.

### PR DESCRIPTION
**Pull request by magnusbaeck**
The code itself was already compatible with the new event API so it was just a matter of adjusting the gemspec.

Fixes #11

### CODE REVIEW

**Comment by ph** [comment]
LGTM, the dependencies ranges seems fine, thanks for reformating the changelog

**Comment by ph** [comment]
I've talked too soon, we need to update the jdk on travis to make the spec run.
like this https://github.com/logstash-plugins/logstash-input-beats/blob/master/.travis.yml#L14

**Comment by magnusbaeck** [comment]
I took the liberty of merging after adding the JDK line since you were happy with the rest. I've also pushed the v4.0.0 tag. Could you administer the release @ph?

**Comment by ph** [comment]
I've release the 4.0.0

@magnusbaeck if you merge PRs don't do the tagging our tool to publish the gem will take care of that and when the tag already exist it will fail.

I will check if I can come up with a better solution for that.

**Comment by magnusbaeck** [comment]
Oh, I didn't know that. Then I understand the exchange on Jan 4 better (when I pushed logstash-filter-prune v3.0.0 and you asked if I had created the tag). Sorry about that, and thanks for the help.

**Pull request merged**
