### PR TITLE
Remove mentions of the non-existent server mode

### PR DESCRIPTION
**Pull request by magnusbaeck**
@logstash-plugins/logstash-core, please review.

### CODE REVIEW

**Comment by magnusbaeck** [comment]
Jenkins, test it.

**Comment by purbon** [comment]
please jenkins, test it.

**Comment by purbon** [comment]
@magnusbaeck the change looks reasonable to me. Can you raise the major version, as this changes the public api and add the change to the changelog? thanks man

**Comment by magnusbaeck** [comment]
> please jenkins, test it.

Was I not polite enough for the bot or is it only core folks that can ask for a Jenkins run?

> Can you raise the major version, as this changes the public api and add the change to the changelog?

Sure. Do you usually step the version and add a changelog entry in a separate commit or in the same commit that drives the version bump?

**Comment by purbon** [comment]
re jenkins, you where polite enough, was a configuration issue that is fix now. Next time if you ask ```please jenkins, test it``` it will run.

re changelog: I usually do all in one commit, but this is your call at the end of the day.

**Comment by magnusbaeck** [comment]
> re changelog: I usually do all in one commit, but this is your call at the end of the day.

Okay, I amended the previous commit. Please have another look.

**Comment by purbon** [comment]
LGTM

**Comment by purbon** [comment]
@magnusbaeck are you considering backporting to the 1.x branch?

**Comment by magnusbaeck** [comment]
> are you considering backporting to the 1.x branch?

1.x branch of Logstash? Will there be any more releases to speak?

**Comment by purbon** [comment]
sorry, ```core-api-v1``` branch of this plugin, this match 1.x logstashes. It does not matter at if we do more releases or not, but users could want to fetch plugin improvements while not updating their logstash.

**Comment by magnusbaeck** [comment]
Okay, fair point. So we'd bump the version from 0.1.x to 1.0.x then I guess? And hope we won't have to bump the major version on that branch ever again? :-)

**Comment by purbon** [comment]
@magnusbaeck I know, is a problem .... you know, versions and cross version support is always complicated. Do you know anything that might help on this? proposals welcome for sure.

**Pull request closed without merging**
